In [66]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [67]:
prj_dir = '/Users/kang-shinwon/dev/personal/sensor_fusion'
calibs_dir = prj_dir + '/sample_data/calibs'
lidar_dir = prj_dir + '/sample_data/points'
image_dir = prj_dir + '/sample_data/images'

In [87]:
# load pcd data 
points = np.fromfile(lidar_dir + '/000031.pcd', '<f4')
points = np.reshape(points, (-1, 4))

# load camera
image = cv2.imread(image_dir + '/000031.png')

# load calibration data
calib_file = open(calibs_dir + '/000031.txt', 'r')
calib_lines = calib_file.readlines()

p0 = np.array(calib_lines[0].strip('\n').split(' ')[1:], dtype=np.float32).reshape(3, 4)
p1 = np.array(calib_lines[1].strip('\n').split(' ')[1:], dtype=np.float32).reshape(3, 4)
p2 = np.array(calib_lines[2].strip('\n').split(' ')[1:], dtype=np.float32).reshape(3, 4)
p3 = np.array(calib_lines[3].strip('\n').split(' ')[1:], dtype=np.float32).reshape(3, 4)
r0_rect = np.array(calib_lines[4].strip('\n').split(' ')[1:], dtype=np.float32).reshape(3, 3)
tr_velo_to_cam = np.array(calib_lines[5].strip('\n').split(' ')[1:], dtype=np.float32).reshape(3, 4)
tr_imu_to_velo = np.array(calib_lines[6].strip('\n').split(' ')[1:], dtype=np.float32).reshape(3, 4)

calib = {
    'p0': p0,
    'p1': p1,   
    'p2': p2,
    'p3': p3,
    'r0_rect': r0_rect,
    'tr_velo_to_cam': tr_velo_to_cam,
    'tr_imu_to_velo': tr_imu_to_velo
}

In [82]:
print('points: {}\n{}'.format(points.shape, points))
print('image: {}\n{}'.format(image.shape, image))
print('calib:\n', calib)

points: (363916,)
[ 1.16853668e+10  8.12648447e+32  1.55159851e-19 ...  9.53472206e+20
 -1.68610879e+30  1.27104336e+11]
image: (375, 1242, 3)
[[[244 159 133]
  [255 175 127]
  [255 192 176]
  ...
  [ 69  91  72]
  [ 66  93  71]
  [ 62  95  75]]

 [[238 187 140]
  [254 205 132]
  [255 224 207]
  ...
  [ 72  82  49]
  [ 74  83  58]
  [ 78  87  75]]

 [[236 223 179]
  [251 223 169]
  [255 239 210]
  ...
  [ 81  88  74]
  [ 88 108 103]
  [ 92 129 152]]

 ...

 [[ 43  28  24]
  [ 37  28  24]
  [ 35  29  23]
  ...
  [ 36  58 255]
  [ 35  58 255]
  [ 36  58 255]]

 [[ 31  25  23]
  [ 32  26  23]
  [ 32  27  23]
  ...
  [ 40  56 255]
  [ 41  58 255]
  [ 40  59 255]]

 [[ 27  27  25]
  [ 31  27  25]
  [ 33  28  23]
  ...
  [ 40  56 255]
  [ 42  57 255]
  [ 42  58 255]]]
calib:
 {'p0': array([[721.5377,   0.    , 609.5593,   0.    ],
       [  0.    , 721.5377, 172.854 ,   0.    ],
       [  0.    ,   0.    ,   1.    ,   0.    ]], dtype=float32), 'p1': array([[ 721.5377,    0.    ,  609.5593, -

In [3]:
def lidar2cam():
    pass

def object_on_image():
    pass

def object_on_lidar():
    pass

def lidar2bev():
    pass